export interface SessionUiHelpersScriptOptions {
	liveChannelId?: string;
}

export function buildSessionUiHelpersScript(options: SessionUiHelpersScriptOptions = {}): string {
	const liveChannelId = JSON.stringify(options.liveChannelId ?? "web");
	return [
		`const SESSION_UI_LIVE_CHANNEL = ${liveChannelId};`,
		"function sessionUiDisplayName(session) {",
		'  if (!session || typeof session !== "object") return "";',
		'  return String(session.sessionName || "").trim();',
		"}",
		"function sessionUiSenderLabel(session) {",
		'  if (!session || typeof session !== "object") return "";',
		'  var senderName = String(session.senderName || "").trim();',
		'  var senderId = String(session.senderId || "").trim();',
		'  if (senderName && senderId && senderName !== senderId) return senderName + " (" + senderId + ")";',
		"  return senderName || senderId;",
		"}",
		"function sessionUiConversationLabel(session) {",
		'  if (!session || typeof session !== "object") return "";',
		'  var conversationName = String(session.conversationName || "").trim();',
		'  var threadId = String(session.threadId || "").trim();',
		'  if (conversationName && threadId && session.conversationType === "thread") return conversationName + " · thread " + threadId;',
		"  if (conversationName) return conversationName;",
		'  return threadId ? "thread " + threadId : "";',
		"}",
		"function sessionUiUniqueItems(items) {",
		"  var seen = new Set();",
		"  return (Array.isArray(items) ? items : []).filter(function(item) {",
		'    if (!item || typeof item !== "object") return false;',
		'    var kind = String(item.kind || "").trim();',
		'    var text = String(item.text || "").trim();',
		"    if (!text) return false;",
		'    var key = kind + ":" + text;',
		"    if (seen.has(key)) return false;",
		"    seen.add(key);",
		"    return true;",
		"  });",
		"}",
		"function sessionUiPrimaryLabel(session, options) {",
		'  if (!session || typeof session !== "object") return "";',
		'  var opts = options && typeof options === "object" ? options : {};',
		"  var explicit = sessionUiDisplayName(session);",
		"  if (explicit) return explicit;",
		'  var fallbackId = String(session.id || "").trim();',
		'  var channel = String(session.channelId || "").trim();',
		"  var conversation = sessionUiConversationLabel(session);",
		"  var sender = sessionUiSenderLabel(session);",
		'  if (!channel) return fallbackId;',
		'  if (channel === SESSION_UI_LIVE_CHANNEL && opts.liveChannelUsesContext !== true) return conversation || fallbackId;',
		"  return sessionUiUniqueItems([",
		'    { kind: "channel", text: channel },',
		'    { kind: "conversation", text: conversation },',
		'    { kind: "sender", text: sender },',
		"  ]).map(function(item) { return item.text; }).join(\" · \") || conversation || sender || fallbackId;",
		"}",
		"function sessionUiContextLabel(session, options) {",
		'  if (!session || typeof session !== "object") return "";',
		'  var opts = options && typeof options === "object" ? options : {};',
		'  var channel = String(session.channelId || "").trim();',
		"  var conversation = sessionUiConversationLabel(session);",
		"  var sender = sessionUiSenderLabel(session);",
		'  if (!channel) return "";',
		'  if (channel === SESSION_UI_LIVE_CHANNEL && opts.includeLiveChannel !== true) return conversation || "";',
		"  return sessionUiUniqueItems([",
		'    { kind: "channel", text: channel },',
		'    { kind: "conversation", text: conversation },',
		'    { kind: "sender", text: sender },',
		"  ]).map(function(item) { return item.text; }).join(\" · \");",
		"}",
		"function sessionUiTeachLabel(session) {",
		'  if (!session || typeof session !== "object") return "";',
		'  var teach = session.teachClarification && typeof session.teachClarification === "object" ? session.teachClarification : null;',
		'  if (!teach) return "";',
		'  var status = String(teach.status || "").trim().toLowerCase();',
		'  if (status === "ready") return "teach ready";',
		'  var nextQuestion = String(teach.nextQuestion || "").trim();',
		'  return nextQuestion ? "teach needs input" : "teach clarifying";',
		"}",
		"function sessionUiChipItems(session, options) {",
		'  if (!session || typeof session !== "object") return [];',
		'  var opts = options && typeof options === "object" ? options : {};',
		'  var channel = String(session.channelId || "").trim();',
		"  var conversation = sessionUiConversationLabel(session);",
		"  var sender = sessionUiSenderLabel(session);",
		"  var teach = sessionUiTeachLabel(session);",
		"  var items = [];",
		'  if (channel && opts.includeChannel !== false && (channel !== SESSION_UI_LIVE_CHANNEL || opts.forceChannel === true)) {',
		'    items.push({ kind: "channel", text: channel });',
		"  }",
		'  if (conversation && opts.includeConversation !== false) items.push({ kind: "conversation", text: conversation });',
		'  if (sender && opts.includeSender === true) items.push({ kind: "sender", text: sender });',
		'  if (teach && opts.includeTeach !== false) items.push({ kind: "teach", text: teach });',
		'  if (opts.readOnly === true && opts.includeReadOnly !== false) items.push({ kind: "state", text: "read-only" });',
		"  return sessionUiUniqueItems(items);",
		"}",
	].join("\n");
}
